/*******************************************************************************
 * Copyright (c) 2012 Cesar Yeep.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the BSD 3-Clause License
 * ("New BSD" or "BSD Simplified") which accompanies this distribution,
 * and is available at
 * http://opensource.org/licenses/BSD-3-Clause
 * 
 * Contributors:
 *     Cesar Yeep - initial API and implementation
 ******************************************************************************/
package testFramework;

import java.io.*;
import cleanJavaTools.CleanJavaChecker;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/** Provides utilities to run a test case in CJC frontend. */
public class TestUtilities {

	public static final String FILENAME = "TempTestFile";
	public static final String PATH = "test"+File.separator+FILENAME+".java";
	
	/** Runs the checker and returns any error generated by it. 
	 *
	 *	@param setUp Provides any neccesary setup for the testcase.
	 *  @param testCase Contains current testcase.
	*/
	public static String runChecker(String setUp, String testCase) {
		testCase = setUp + "\n\n" + testCase;
		return runChecker(testCase);
	}

	
	/** Runs the checker and returns any error generated by it. 
	 *
	 *  @param testCase Contains current testcase.
	*/
	public static String runChecker(String testCase) {
		try{
			createFile(createStub(testCase));
		} 
		catch (IOException e){
			System.err.println("Error creating file: "+e.getMessage());
		}
		String checkerOutput = new CleanJavaChecker(new String[]{PATH}).getErrorString();
		/*
		try{
			deleteFile();
		}
		catch (IOException e){
			System.err.println("Error deleting file: "+e.getMessage());
		}
		*/
		return	checkerOutput;
	}
	
	/** Creates a stub for the testcase. */
	private static String createStub(String testCase) {
		String stub = "public class " + FILENAME +"{\n";
		stub+=testCase;
		stub+="\n\tpublic void foo(){}\n}";
		return stub;
	}
	
	/** Creates a new java file from the stub. */
	private static void createFile(String code) throws IOException {
		File file = new File(PATH);
		FileOutputStream fop = new FileOutputStream(file);

		if(file.exists()){
			fop.write(code.getBytes());

			fop.flush();
			fop.close();
        }
	}
	
	/** Delete temp file. */
	private static void deleteFile() throws IOException {
		Path path = Paths.get(PATH);
		Files.delete(path);
	}

}